version: '3'
services:
  # Lift Up Backend
  liftup-backend:
    container_name: liftup-backend
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3010:3010"
    command: "npm run start:dev"
    volumes:
      - /var/index_uploads:/app/public/index_uploads
      - /var/contacts_uploads:/app/public/contacts_uploads
      - ./prisma:/app/prisma
    stdin_open: true
    tty: true

volumes:
  prisma:
  index_uploads:
  contacts_uploads:
